// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'localhost:8080/' | (string & {})
}

export type TaskActionItemResponse = {
  created_at?: string
  description?: string
  end_time?: string
  kind?: string
  start_time?: string
  status?: TaskActionItemStatus
  title?: string
  updated_at?: string
  user_id?: string
  uuid?: string
}

export type TaskActionItemStatus =
  | 'completed'
  | 'progress_70'
  | 'progress_30'
  | 'not_started'

export type TaskCreateRequest = {
  description?: string
  end_time: string
  kind: string
  start_time: string
  status: TaskActionItemStatus
  title: string
  user_id: string
}

export type TaskUpdateRequest = {
  description?: string
  end_time?: string
  kind?: string
  start_time?: string
  status?: TaskActionItemStatus
  title?: string
}

export type GetApiV1ActionItemsData = {
  body?: never
  path?: never
  query: {
    /**
     * ユーザーUUID
     */
    user_id: string
  }
  url: '/api/v1/action-items'
}

export type GetApiV1ActionItemsErrors = {
  /**
   * Bad Request
   */
  400: {
    [key: string]: string
  }
  /**
   * Internal Server Error
   */
  500: {
    [key: string]: string
  }
}

export type GetApiV1ActionItemsError =
  GetApiV1ActionItemsErrors[keyof GetApiV1ActionItemsErrors]

export type GetApiV1ActionItemsResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: Array<TaskActionItemResponse>
  }
}

export type GetApiV1ActionItemsResponse =
  GetApiV1ActionItemsResponses[keyof GetApiV1ActionItemsResponses]

export type PostApiV1ActionItemsData = {
  /**
   * アクションアイテム情報
   */
  body: TaskCreateRequest
  path?: never
  query?: never
  url: '/api/v1/action-items'
}

export type PostApiV1ActionItemsErrors = {
  /**
   * Bad Request
   */
  400: {
    [key: string]: string
  }
  /**
   * Internal Server Error
   */
  500: {
    [key: string]: string
  }
}

export type PostApiV1ActionItemsError =
  PostApiV1ActionItemsErrors[keyof PostApiV1ActionItemsErrors]

export type PostApiV1ActionItemsResponses = {
  /**
   * Created
   */
  201: {
    [key: string]: TaskActionItemResponse
  }
}

export type PostApiV1ActionItemsResponse =
  PostApiV1ActionItemsResponses[keyof PostApiV1ActionItemsResponses]

export type DeleteApiV1ActionItemsByUuidData = {
  body?: never
  path: {
    /**
     * アクションアイテムUUID
     */
    uuid: string
  }
  query?: never
  url: '/api/v1/action-items/{uuid}'
}

export type DeleteApiV1ActionItemsByUuidErrors = {
  /**
   * Bad Request
   */
  400: {
    [key: string]: string
  }
  /**
   * Not Found
   */
  404: {
    [key: string]: string
  }
  /**
   * Internal Server Error
   */
  500: {
    [key: string]: string
  }
}

export type DeleteApiV1ActionItemsByUuidError =
  DeleteApiV1ActionItemsByUuidErrors[keyof DeleteApiV1ActionItemsByUuidErrors]

export type DeleteApiV1ActionItemsByUuidResponses = {
  /**
   * No Content
   */
  204: unknown
}

export type GetApiV1ActionItemsByUuidData = {
  body?: never
  path: {
    /**
     * アクションアイテムUUID
     */
    uuid: string
  }
  query?: never
  url: '/api/v1/action-items/{uuid}'
}

export type GetApiV1ActionItemsByUuidErrors = {
  /**
   * Bad Request
   */
  400: {
    [key: string]: string
  }
  /**
   * Not Found
   */
  404: {
    [key: string]: string
  }
  /**
   * Internal Server Error
   */
  500: {
    [key: string]: string
  }
}

export type GetApiV1ActionItemsByUuidError =
  GetApiV1ActionItemsByUuidErrors[keyof GetApiV1ActionItemsByUuidErrors]

export type GetApiV1ActionItemsByUuidResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: TaskActionItemResponse
  }
}

export type GetApiV1ActionItemsByUuidResponse =
  GetApiV1ActionItemsByUuidResponses[keyof GetApiV1ActionItemsByUuidResponses]

export type PutApiV1ActionItemsByUuidData = {
  /**
   * 更新内容
   */
  body: TaskUpdateRequest
  path: {
    /**
     * アクションアイテムUUID
     */
    uuid: string
  }
  query?: never
  url: '/api/v1/action-items/{uuid}'
}

export type PutApiV1ActionItemsByUuidErrors = {
  /**
   * Bad Request
   */
  400: {
    [key: string]: string
  }
  /**
   * Not Found
   */
  404: {
    [key: string]: string
  }
  /**
   * Internal Server Error
   */
  500: {
    [key: string]: string
  }
}

export type PutApiV1ActionItemsByUuidError =
  PutApiV1ActionItemsByUuidErrors[keyof PutApiV1ActionItemsByUuidErrors]

export type PutApiV1ActionItemsByUuidResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: TaskActionItemResponse
  }
}

export type PutApiV1ActionItemsByUuidResponse =
  PutApiV1ActionItemsByUuidResponses[keyof PutApiV1ActionItemsByUuidResponses]

export type GetHealthData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type GetHealthResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: boolean
  }
}

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses]
