// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'localhost:8080/' | (string & {})
}

export type GetHealthData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type GetHealthResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: boolean
  }
}

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses]
